### ISSUE TITLE
Multiple issues. Are pull requests still accepted?

### ISSUE THREAD

**Issue by jrson83** [csi-lk/package-labeler#5]
The labeler is exactly what I need, but I'm having multiple issues with it.

1. `Unexpected input(s) 'name', valid inputs are ['repo-token', 'workspace', 'prefix']`

It seems that the parameter `name` does not exist at all.

2. `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: csi-lk/package-labeler@v1.0.1`

The `action.yml` node version should be updated from `node12` to `node16`.

3. The deps should be updated.

When updating the deps, code modification is required. Should switch to package `@octokit/rest` and use:

```ts
import { Octokit } from '@octokit/rest';

const client = new Octokit({
  auth: token
});
```

4. The docs describe how to use `prefix: "pkg: "`. There is a space behind the colon, so the applied tag should be `pkg: core`. However the space gets trimmed from the prefix and the applied tag is `pkg:core` without space..

Are pull requests still accepted? If so, I would really like to contribute to fix the issues. As an alternative I would fork the repo, apply the patches and release a new workflow. I would prefer the first one.

**Comment by csi-lk** [comment]
Hey mate, absolutely, if you are up for improving / fixing it i'll set you as a maintainer after the PRs come in 😊
